version: '3.8'

services:
  postgres-dev:
    image: postgres:15-alpine
    container_name: aptechka_db_dev
    environment:
      POSTGRES_DB: aptechka_dev
      POSTGRES_USER: ${DB_USER:-aptechka_user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-aptechka_password}
    ports:
      - "5432:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-aptechka_user} -d aptechka_dev"]
      interval: 30s
      timeout: 10s
      retries: 3

  bot-dev:
    build: .
    container_name: aptechka_bot_dev
    env_file: .env.dev
    ports:
      - "8080:8080"
    depends_on:
      postgres-dev:
        condition: service_healthy
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_dev_data:
