version: '3.8'

services:
  postgres-prod:
    image: postgres:15-alpine
    container_name: aptechka_db_prod
    environment:
      POSTGRES_DB: aptechka_prod
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - postgres_prod_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d aptechka_prod"]
      interval: 30s
      timeout: 10s
      retries: 3

  bot-prod:
    image: ghcr.io/username/aptechka-bot:latest
    container_name: aptechka_bot_prod
    env_file: .env.prod
    ports:
      - "8081:8080"
    depends_on:
      postgres-prod:
        condition: service_healthy
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_prod_data:
